blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/pedromdev/ts-to-json-schema/discussions
    about: Please use Discussions for questions and general support
  - name: Documentation
    url: https://pedromdev.github.io/ts-to-json-schema/
    about: Check the documentation for information on how to use TS to JSON Schema 