name: Unit Tests
on:
  - push
  - pull_request
jobs:
  tests:
    name: Node.js ${{ matrix.node-version }} | TypeScript ${{ matrix.typescript-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
          - 14
          - 12
        typescript-version:
          - '^5.1.0'
          - '~5.0.0'
          - '^4.1.0'
          - '~4.0.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run start
      - run: npm install typescript@${{ matrix.typescript-version }}
      - run: npm run build:prod
      - run: npm run test
