name: Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package.json'
      - 'yarn.lock'
      - 'jest.config.js'
      - 'tsconfig.json'
  pull_request_target:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package.json'
      - 'yarn.lock'
      - 'jest.config.js'
      - 'tsconfig.json'
jobs:
  tests:
    name: Node.js ${{ matrix.node-version }} | TypeScript ${{ matrix.typescript-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
          - 14
        typescript-version:
          - '^5.1.0'
          - '~5.0.0'
          - '^4.1.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn start
      - run: yarn add -W -D typescript@${{ matrix.typescript-version }}
      - run: yarn build:prod
      - run: yarn test
